# Generated by Django 4.0.1 on 2022-01-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('title', models.TextField()),
                ('link', models.TextField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=5000)),
                ('num_responses', models.CharField(max_length=1000)),
                ('num_claps', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=1000)),
            ],
        ),
    ]
